# Generated by Django 3.1.5 on 2021-02-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp', 'comment_text']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='', verbose_name='comment text'),
        ),
    ]
