# Generated by Django 3.1.5 on 2021-02-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210214_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'unpublished'), (2, 'published')]),
        ),
    ]
