# Generated by Django 3.1.5 on 2021-02-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'unpublished'), (2, 'published')]),
        ),
    ]
