# Generated by Django 3.1.5 on 2021-02-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210216_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='mail'),
        ),
    ]
